# Generated by Django 3.2.21 on 2023-09-26 06:12

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20230925_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(
                upload_to=core.models.image_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
