# Generated by Django 3.2.21 on 2023-09-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_uploadedimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagelink",
            name="uploaded_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="core.uploadedimage",
            ),
        ),
    ]
