# Generated by Django 3.2.21 on 2023-09-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_imagelink_uploaded_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagelink",
            name="type",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("expiring", "Expiring"),
                    ("thumbnail", "Thumbnail"),
                ],
                default="thumbnail",
                max_length=10,
            ),
        ),
    ]
